// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.850
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Mark menggambar logo bunga sakura (kelopak runcing, bukan bulat).
func Mark() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<svg class=\"mark\" viewBox=\"0 0 40 40\" aria-hidden=\"true\"><g transform=\"translate(20 20)\"><g fill=\"var(--sakura)\"><path d=\"M0 0 C -5.5 -4 -5 -9.5 0 -13 C 5 -9.5 5.5 -4 0 0 Z\"></path> <path d=\"M0 0 C -5.5 -4 -5 -9.5 0 -13 C 5 -9.5 5.5 -4 0 0 Z\" transform=\"rotate(72)\"></path> <path d=\"M0 0 C -5.5 -4 -5 -9.5 0 -13 C 5 -9.5 5.5 -4 0 0 Z\" transform=\"rotate(144)\"></path> <path d=\"M0 0 C -5.5 -4 -5 -9.5 0 -13 C 5 -9.5 5.5 -4 0 0 Z\" transform=\"rotate(216)\"></path> <path d=\"M0 0 C -5.5 -4 -5 -9.5 0 -13 C 5 -9.5 5.5 -4 0 0 Z\" transform=\"rotate(288)\"></path></g> <circle r=\"3.2\" fill=\"var(--ink)\"></circle></g></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
