// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.850
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Mark menggambar logo RT (sakura di atas lingkaran gelap).
func Mark() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<svg class=\"mark\" viewBox=\"0 0 44 44\" width=\"36\" height=\"36\" aria-hidden=\"true\"><circle cx=\"22\" cy=\"22\" r=\"21\" fill=\"rgba(0,0,0,.22)\"></circle> <g transform=\"translate(22 22)\"><g fill=\"#F6C9D6\" stroke=\"#C98098\" stroke-width=\"1\"><ellipse rx=\"6\" ry=\"10.5\" cy=\"-9.5\"></ellipse> <ellipse rx=\"6\" ry=\"10.5\" cy=\"-9.5\" transform=\"rotate(72)\"></ellipse> <ellipse rx=\"6\" ry=\"10.5\" cy=\"-9.5\" transform=\"rotate(144)\"></ellipse> <ellipse rx=\"6\" ry=\"10.5\" cy=\"-9.5\" transform=\"rotate(216)\"></ellipse> <ellipse rx=\"6\" ry=\"10.5\" cy=\"-9.5\" transform=\"rotate(288)\"></ellipse></g> <circle r=\"4\" fill=\"#C79A2E\"></circle></g></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
