// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.850
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "sakuragakure/internal/web/components"

func Beranda() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"stack\"><div class=\"hero\"><div class=\"hero-text\"><h1>Kabar, kas, dan kegiatan warga <span class=\"soft\">RT 06 Sakura.</span></h1><p class=\"muted\">120 rumah di tiga gang, Cluster Sakura, Grand Cikarang City. Setiap rupiah iuran tercatat di sini, lengkap dengan notanya.</p><div class=\"row\" style=\"flex-wrap:wrap\"><button class=\"btn\" type=\"button\">Lihat laporan kas</button><button class=\"btn ghost\" type=\"button\">Hubungi pengurus</button></div></div></div><div class=\"grid3\"><div class=\"pos main\"><span class=\"small muted\">Saldo kas RT</span><span class=\"big num\">Rp 0</span><span class=\"tiny muted\">belum ada mutasi</span></div><div class=\"pos\"><span class=\"small muted\">Dana sosial</span><span class=\"big num\">Rp 0</span><span class=\"tiny faint\">dialokasikan dari kas RT</span></div><div class=\"pos\"><span class=\"small muted\">Rukun kematian</span><span class=\"big num\">Rp 0</span><span class=\"tiny faint\">iuran Rp50.000 per KK</span></div></div><section class=\"card\"><div class=\"section-h\"><h2>Iuran per gang</h2><p class=\"small muted\">Satu kelopak satu rumah wajib iuran. Nama dan alamat tidak ditampilkan.</p></div><p class=\"small muted\">Kelopak, grafik, dan mutasi diisi pada fase berikutnya.</p></section></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.Layout("Beranda · RT 06 / RW 28 Sakura").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
