// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package db

import (
	"context"
	"database/sql"
)

const addUserPeran = `-- name: AddUserPeran :exec
INSERT OR IGNORE INTO user_peran (user_id, peran, gang, urutan) VALUES (?, ?, ?, ?)
`

type AddUserPeranParams struct {
	UserID int64
	Peran  string
	Gang   int64
	Urutan int64
}

func (q *Queries) AddUserPeran(ctx context.Context, arg AddUserPeranParams) error {
	_, err := q.db.ExecContext(ctx, addUserPeran,
		arg.UserID,
		arg.Peran,
		arg.Gang,
		arg.Urutan,
	)
	return err
}

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM album WHERE id = ?
`

func (q *Queries) DeleteAlbum(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlbum, id)
	return err
}

const deleteAlbumFoto = `-- name: DeleteAlbumFoto :exec
DELETE FROM album_foto WHERE album_id = ? AND media_id = ?
`

type DeleteAlbumFotoParams struct {
	AlbumID int64
	MediaID int64
}

func (q *Queries) DeleteAlbumFoto(ctx context.Context, arg DeleteAlbumFotoParams) error {
	_, err := q.db.ExecContext(ctx, deleteAlbumFoto, arg.AlbumID, arg.MediaID)
	return err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media WHERE id = ?
`

func (q *Queries) DeleteMedia(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMedia, id)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT a.id, a.user_id, COALESCE(u.nama, '') AS user_nama, a.aksi, a.objek, a.objek_id, a.detail, a.ip, a.at
FROM audit_log a
LEFT JOIN user u ON u.id = a.user_id
ORDER BY a.id DESC
LIMIT 200
`

type ListAuditRow struct {
	ID       int64
	UserID   sql.NullInt64
	UserNama string
	Aksi     string
	Objek    string
	ObjekID  sql.NullString
	Detail   sql.NullString
	Ip       sql.NullString
	At       string
}

func (q *Queries) ListAudit(ctx context.Context) ([]ListAuditRow, error) {
	rows, err := q.db.QueryContext(ctx, listAudit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditRow
	for rows.Next() {
		var i ListAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserNama,
			&i.Aksi,
			&i.Objek,
			&i.ObjekID,
			&i.Detail,
			&i.Ip,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFotoAlbum = `-- name: ListFotoAlbum :many
SELECT media_id FROM album_foto WHERE album_id = ?
`

func (q *Queries) ListFotoAlbum(ctx context.Context, albumID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listFotoAlbum, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var media_id int64
		if err := rows.Scan(&media_id); err != nil {
			return nil, err
		}
		items = append(items, media_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedia = `-- name: ListMedia :many
SELECT id, path, thumb_path, mime, ukuran, akses, pemilik_user_id, dibuat_at FROM media ORDER BY id DESC LIMIT 200
`

type ListMediaRow struct {
	ID            int64
	Path          string
	ThumbPath     sql.NullString
	Mime          string
	Ukuran        int64
	Akses         string
	PemilikUserID sql.NullInt64
	DibuatAt      string
}

func (q *Queries) ListMedia(ctx context.Context) ([]ListMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, listMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMediaRow
	for rows.Next() {
		var i ListMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.ThumbPath,
			&i.Mime,
			&i.Ukuran,
			&i.Akses,
			&i.PemilikUserID,
			&i.DibuatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserPeran = `-- name: RemoveUserPeran :exec
DELETE FROM user_peran WHERE user_id = ? AND peran = ? AND gang = ?
`

type RemoveUserPeranParams struct {
	UserID int64
	Peran  string
	Gang   int64
}

func (q *Queries) RemoveUserPeran(ctx context.Context, arg RemoveUserPeranParams) error {
	_, err := q.db.ExecContext(ctx, removeUserPeran, arg.UserID, arg.Peran, arg.Gang)
	return err
}

const toggleUserAktif = `-- name: ToggleUserAktif :exec
UPDATE user SET aktif = ? WHERE id = ?
`

type ToggleUserAktifParams struct {
	Aktif int64
	ID    int64
}

func (q *Queries) ToggleUserAktif(ctx context.Context, arg ToggleUserAktifParams) error {
	_, err := q.db.ExecContext(ctx, toggleUserAktif, arg.Aktif, arg.ID)
	return err
}

const userPeranList = `-- name: UserPeranList :many
SELECT peran, gang FROM user_peran WHERE user_id = ? ORDER BY urutan
`

type UserPeranListRow struct {
	Peran string
	Gang  int64
}

func (q *Queries) UserPeranList(ctx context.Context, userID int64) ([]UserPeranListRow, error) {
	rows, err := q.db.QueryContext(ctx, userPeranList, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPeranListRow
	for rows.Next() {
		var i UserPeranListRow
		if err := rows.Scan(&i.Peran, &i.Gang); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
