// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: iuran.sql

package db

import (
	"context"
	"database/sql"
)

const gridGang = `-- name: GridGang :many
SELECT r.id, r.alamat, r.blok, r.nomor, r.status, r.bebas_iuran_alasan,
       COALESCE(ph.nama_kk, '') AS nama_kk,
       COALESCE(p.status, '') AS bayar_status
FROM rumah r
LEFT JOIN penghuni ph ON ph.rumah_id = r.id AND ph.selesai IS NULL
LEFT JOIN tagihan t ON t.rumah_id = r.id AND t.jenis = 'kas' AND t.periode = ?
LEFT JOIN pembayaran p ON p.tagihan_id = t.id
WHERE r.gang = ?
ORDER BY r.blok, r.nomor
`

type GridGangParams struct {
	Periode string
	Gang    int64
}

type GridGangRow struct {
	ID               int64
	Alamat           string
	Blok             string
	Nomor            string
	Status           string
	BebasIuranAlasan sql.NullString
	NamaKk           string
	BayarStatus      string
}

func (q *Queries) GridGang(ctx context.Context, arg GridGangParams) ([]GridGangRow, error) {
	rows, err := q.db.QueryContext(ctx, gridGang, arg.Periode, arg.Gang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GridGangRow
	for rows.Next() {
		var i GridGangRow
		if err := rows.Scan(
			&i.ID,
			&i.Alamat,
			&i.Blok,
			&i.Nomor,
			&i.Status,
			&i.BebasIuranAlasan,
			&i.NamaKk,
			&i.BayarStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heldPerPeriode = `-- name: HeldPerPeriode :many
SELECT t.periode,
       CAST(COUNT(*) AS INTEGER) AS jumlah,
       CAST(SUM(t.nominal) AS INTEGER) AS total
FROM pembayaran p
JOIN tagihan t ON t.id = p.tagihan_id
JOIN rumah r ON r.id = t.rumah_id
WHERE p.status = 'dipegang' AND r.gang = ?
GROUP BY t.periode
ORDER BY t.periode DESC
`

type HeldPerPeriodeRow struct {
	Periode string
	Jumlah  int64
	Total   int64
}

func (q *Queries) HeldPerPeriode(ctx context.Context, gang int64) ([]HeldPerPeriodeRow, error) {
	rows, err := q.db.QueryContext(ctx, heldPerPeriode, gang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeldPerPeriodeRow
	for rows.Next() {
		var i HeldPerPeriodeRow
		if err := rows.Scan(&i.Periode, &i.Jumlah, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setoranMenunggu = `-- name: SetoranMenunggu :many
SELECT s.id, s.gang, s.periode, s.total, s.koordinator_id, u.nama AS koordinator, s.dibuat_at
FROM setoran s
JOIN user u ON u.id = s.koordinator_id
WHERE s.status = 'menunggu'
ORDER BY s.periode, s.gang
`

type SetoranMenungguRow struct {
	ID            int64
	Gang          int64
	Periode       string
	Total         int64
	KoordinatorID int64
	Koordinator   string
	DibuatAt      string
}

func (q *Queries) SetoranMenunggu(ctx context.Context) ([]SetoranMenungguRow, error) {
	rows, err := q.db.QueryContext(ctx, setoranMenunggu)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SetoranMenungguRow
	for rows.Next() {
		var i SetoranMenungguRow
		if err := rows.Scan(
			&i.ID,
			&i.Gang,
			&i.Periode,
			&i.Total,
			&i.KoordinatorID,
			&i.Koordinator,
			&i.DibuatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setoranRiwayat = `-- name: SetoranRiwayat :many
SELECT s.id, s.periode, s.total, s.status, s.dibuat_at, s.catatan
FROM setoran s
WHERE s.gang = ?
ORDER BY s.dibuat_at DESC
`

type SetoranRiwayatRow struct {
	ID       int64
	Periode  string
	Total    int64
	Status   string
	DibuatAt string
	Catatan  sql.NullString
}

func (q *Queries) SetoranRiwayat(ctx context.Context, gang int64) ([]SetoranRiwayatRow, error) {
	rows, err := q.db.QueryContext(ctx, setoranRiwayat, gang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SetoranRiwayatRow
	for rows.Next() {
		var i SetoranRiwayatRow
		if err := rows.Scan(
			&i.ID,
			&i.Periode,
			&i.Total,
			&i.Status,
			&i.DibuatAt,
			&i.Catatan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
