// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: kas.sql

package db

import (
	"context"
	"database/sql"
)

const dansosTahun = `-- name: DansosTahun :one
SELECT COUNT(*) AS jumlah,
       CAST(COALESCE(SUM(nominal), 0) AS INTEGER) AS total
FROM mutasi
WHERE pos_id = 'dana_sosial' AND arah = 'keluar' AND substr(tanggal, 1, 4) = ?
`

type DansosTahunRow struct {
	Jumlah int64
	Total  int64
}

func (q *Queries) DansosTahun(ctx context.Context, tanggal string) (DansosTahunRow, error) {
	row := q.db.QueryRowContext(ctx, dansosTahun, tanggal)
	var i DansosTahunRow
	err := row.Scan(&i.Jumlah, &i.Total)
	return i, err
}

const grafikKasBulanan = `-- name: GrafikKasBulanan :many
SELECT substr(tanggal, 1, 7) AS bulan,
       CAST(COALESCE(SUM(CASE WHEN arah = 'masuk' THEN nominal ELSE 0 END), 0) AS INTEGER) AS masuk,
       CAST(COALESCE(SUM(CASE WHEN arah = 'keluar' THEN nominal ELSE 0 END), 0) AS INTEGER) AS keluar
FROM mutasi
WHERE pos_id = 'kas_rt' AND COALESCE(ref_tipe, '') != 'alokasi'
GROUP BY bulan
ORDER BY bulan
`

type GrafikKasBulananRow struct {
	Bulan  string
	Masuk  int64
	Keluar int64
}

func (q *Queries) GrafikKasBulanan(ctx context.Context) ([]GrafikKasBulananRow, error) {
	rows, err := q.db.QueryContext(ctx, grafikKasBulanan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GrafikKasBulananRow
	for rows.Next() {
		var i GrafikKasBulananRow
		if err := rows.Scan(&i.Bulan, &i.Masuk, &i.Keluar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kelopakGang = `-- name: KelopakGang :many
SELECT r.gang,
       CAST(COALESCE(SUM(CASE WHEN p.status = 'diterima' THEN 1 ELSE 0 END), 0) AS INTEGER) AS diterima,
       CAST(COALESCE(SUM(CASE WHEN p.status IN ('dipegang','disetor','menunggu_verifikasi') THEN 1 ELSE 0 END), 0) AS INTEGER) AS dipegang
FROM rumah r
LEFT JOIN tagihan t ON t.rumah_id = r.id AND t.jenis = 'kas' AND t.periode = ?
LEFT JOIN pembayaran p ON p.tagihan_id = t.id
WHERE r.status != 'kosong' AND r.bebas_iuran_alasan IS NULL
GROUP BY r.gang
ORDER BY r.gang
`

type KelopakGangRow struct {
	Gang     int64
	Diterima int64
	Dipegang int64
}

func (q *Queries) KelopakGang(ctx context.Context, periode string) ([]KelopakGangRow, error) {
	rows, err := q.db.QueryContext(ctx, kelopakGang, periode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KelopakGangRow
	for rows.Next() {
		var i KelopakGangRow
		if err := rows.Scan(&i.Gang, &i.Diterima, &i.Dipegang); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mutasiLaporan = `-- name: MutasiLaporan :many
SELECT m.tanggal, p.nama AS pos, m.arah, m.nominal, m.kategori, m.keterangan_publik
FROM mutasi m
JOIN pos_dana p ON p.id = m.pos_id
ORDER BY m.tanggal, m.id
`

type MutasiLaporanRow struct {
	Tanggal          string
	Pos              string
	Arah             string
	Nominal          int64
	Kategori         string
	KeteranganPublik string
}

func (q *Queries) MutasiLaporan(ctx context.Context) ([]MutasiLaporanRow, error) {
	rows, err := q.db.QueryContext(ctx, mutasiLaporan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MutasiLaporanRow
	for rows.Next() {
		var i MutasiLaporanRow
		if err := rows.Scan(
			&i.Tanggal,
			&i.Pos,
			&i.Arah,
			&i.Nominal,
			&i.Kategori,
			&i.KeteranganPublik,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mutasiPublik = `-- name: MutasiPublik :many
SELECT m.id, m.tanggal, m.arah, m.nominal, m.kategori, m.keterangan_publik, p.nama AS pos_nama
FROM mutasi m
JOIN pos_dana p ON p.id = m.pos_id
ORDER BY m.tanggal DESC, m.id DESC
LIMIT ?
`

type MutasiPublikRow struct {
	ID               int64
	Tanggal          string
	Arah             string
	Nominal          int64
	Kategori         string
	KeteranganPublik string
	PosNama          string
}

func (q *Queries) MutasiPublik(ctx context.Context, limit int64) ([]MutasiPublikRow, error) {
	rows, err := q.db.QueryContext(ctx, mutasiPublik, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MutasiPublikRow
	for rows.Next() {
		var i MutasiPublikRow
		if err := rows.Scan(
			&i.ID,
			&i.Tanggal,
			&i.Arah,
			&i.Nominal,
			&i.Kategori,
			&i.KeteranganPublik,
			&i.PosNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mutasiSemua = `-- name: MutasiSemua :many
SELECT m.id, m.tanggal, m.arah, m.nominal, m.kategori, m.keterangan, m.keterangan_publik,
       p.nama AS pos_nama, m.nota_media_id
FROM mutasi m
JOIN pos_dana p ON p.id = m.pos_id
ORDER BY m.tanggal DESC, m.id DESC
LIMIT ?
`

type MutasiSemuaRow struct {
	ID               int64
	Tanggal          string
	Arah             string
	Nominal          int64
	Kategori         string
	Keterangan       string
	KeteranganPublik string
	PosNama          string
	NotaMediaID      sql.NullInt64
}

func (q *Queries) MutasiSemua(ctx context.Context, limit int64) ([]MutasiSemuaRow, error) {
	rows, err := q.db.QueryContext(ctx, mutasiSemua, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MutasiSemuaRow
	for rows.Next() {
		var i MutasiSemuaRow
		if err := rows.Scan(
			&i.ID,
			&i.Tanggal,
			&i.Arah,
			&i.Nominal,
			&i.Kategori,
			&i.Keterangan,
			&i.KeteranganPublik,
			&i.PosNama,
			&i.NotaMediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nominalDiKoordinator = `-- name: NominalDiKoordinator :one
SELECT CAST(COALESCE(SUM(t.nominal), 0) AS INTEGER) AS total
FROM pembayaran p
JOIN tagihan t ON t.id = p.tagihan_id
WHERE p.status IN ('dipegang','disetor','menunggu_verifikasi')
`

func (q *Queries) NominalDiKoordinator(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nominalDiKoordinator)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const posDanaList = `-- name: PosDanaList :many
SELECT id, nama, publik FROM pos_dana ORDER BY id
`

func (q *Queries) PosDanaList(ctx context.Context) ([]PosDana, error) {
	rows, err := q.db.QueryContext(ctx, posDanaList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PosDana
	for rows.Next() {
		var i PosDana
		if err := rows.Scan(&i.ID, &i.Nama, &i.Publik); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saldoPos = `-- name: SaldoPos :one
SELECT CAST(COALESCE(SUM(CASE WHEN arah = 'masuk' THEN nominal ELSE -nominal END), 0) AS INTEGER) AS saldo
FROM mutasi
WHERE pos_id = ?
`

func (q *Queries) SaldoPos(ctx context.Context, posID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, saldoPos, posID)
	var saldo int64
	err := row.Scan(&saldo)
	return saldo, err
}

const saldoPosis = `-- name: SaldoPosis :many
SELECT pos_id,
       CAST(COALESCE(SUM(CASE WHEN arah = 'masuk' THEN nominal ELSE -nominal END), 0) AS INTEGER) AS saldo
FROM mutasi
GROUP BY pos_id
`

type SaldoPosisRow struct {
	PosID string
	Saldo int64
}

func (q *Queries) SaldoPosis(ctx context.Context) ([]SaldoPosisRow, error) {
	rows, err := q.db.QueryContext(ctx, saldoPosis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaldoPosisRow
	for rows.Next() {
		var i SaldoPosisRow
		if err := rows.Scan(&i.PosID, &i.Saldo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wajibIuranPerGang = `-- name: WajibIuranPerGang :many
SELECT gang, COUNT(*) AS total
FROM rumah
WHERE status != 'kosong' AND bebas_iuran_alasan IS NULL
GROUP BY gang
ORDER BY gang
`

type WajibIuranPerGangRow struct {
	Gang  int64
	Total int64
}

func (q *Queries) WajibIuranPerGang(ctx context.Context) ([]WajibIuranPerGangRow, error) {
	rows, err := q.db.QueryContext(ctx, wajibIuranPerGang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WajibIuranPerGangRow
	for rows.Next() {
		var i WajibIuranPerGangRow
		if err := rows.Scan(&i.Gang, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
