// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: konten.sql

package db

import (
	"context"
	"database/sql"
)

const agendaMendatang = `-- name: AgendaMendatang :many
SELECT judul, keterangan, mulai, tingkat FROM agenda WHERE mulai >= ? ORDER BY mulai LIMIT ?
`

type AgendaMendatangParams struct {
	Mulai string
	Limit int64
}

type AgendaMendatangRow struct {
	Judul      string
	Keterangan sql.NullString
	Mulai      string
	Tingkat    string
}

func (q *Queries) AgendaMendatang(ctx context.Context, arg AgendaMendatangParams) ([]AgendaMendatangRow, error) {
	rows, err := q.db.QueryContext(ctx, agendaMendatang, arg.Mulai, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgendaMendatangRow
	for rows.Next() {
		var i AgendaMendatangRow
		if err := rows.Scan(
			&i.Judul,
			&i.Keterangan,
			&i.Mulai,
			&i.Tingkat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const albumBySlug = `-- name: AlbumBySlug :one
SELECT id, judul, slug, tanggal, cerita, sampul_media_id FROM album WHERE slug = ?
`

type AlbumBySlugRow struct {
	ID            int64
	Judul         string
	Slug          string
	Tanggal       string
	Cerita        sql.NullString
	SampulMediaID sql.NullInt64
}

func (q *Queries) AlbumBySlug(ctx context.Context, slug string) (AlbumBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, albumBySlug, slug)
	var i AlbumBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Judul,
		&i.Slug,
		&i.Tanggal,
		&i.Cerita,
		&i.SampulMediaID,
	)
	return i, err
}

const fotoAlbum = `-- name: FotoAlbum :many
SELECT af.media_id, af.keterangan, af.urutan FROM album_foto af WHERE af.album_id = ? ORDER BY af.urutan, af.media_id
`

type FotoAlbumRow struct {
	MediaID    int64
	Keterangan sql.NullString
	Urutan     int64
}

func (q *Queries) FotoAlbum(ctx context.Context, albumID int64) ([]FotoAlbumRow, error) {
	rows, err := q.db.QueryContext(ctx, fotoAlbum, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FotoAlbumRow
	for rows.Next() {
		var i FotoAlbumRow
		if err := rows.Scan(&i.MediaID, &i.Keterangan, &i.Urutan); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const iuranRumah = `-- name: IuranRumah :many
SELECT t.periode, COALESCE(p.status, '') AS bayar_status, t.nominal
FROM tagihan t
LEFT JOIN pembayaran p ON p.tagihan_id = t.id
WHERE t.rumah_id = ? AND t.jenis = 'kas'
ORDER BY t.periode
`

type IuranRumahRow struct {
	Periode     string
	BayarStatus string
	Nominal     int64
}

func (q *Queries) IuranRumah(ctx context.Context, rumahID int64) ([]IuranRumahRow, error) {
	rows, err := q.db.QueryContext(ctx, iuranRumah, rumahID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IuranRumahRow
	for rows.Next() {
		var i IuranRumahRow
		if err := rows.Scan(&i.Periode, &i.BayarStatus, &i.Nominal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbum = `-- name: ListAlbum :many
SELECT id, judul, slug, tanggal, cerita, sampul_media_id FROM album ORDER BY tanggal DESC
`

type ListAlbumRow struct {
	ID            int64
	Judul         string
	Slug          string
	Tanggal       string
	Cerita        sql.NullString
	SampulMediaID sql.NullInt64
}

func (q *Queries) ListAlbum(ctx context.Context) ([]ListAlbumRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumRow
	for rows.Next() {
		var i ListAlbumRow
		if err := rows.Scan(
			&i.ID,
			&i.Judul,
			&i.Slug,
			&i.Tanggal,
			&i.Cerita,
			&i.SampulMediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAturan = `-- name: ListAturan :many
SELECT id, bab, judul, isi_md, urutan FROM aturan_pasal ORDER BY urutan
`

func (q *Queries) ListAturan(ctx context.Context) ([]AturanPasal, error) {
	rows, err := q.db.QueryContext(ctx, listAturan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AturanPasal
	for rows.Next() {
		var i AturanPasal
		if err := rows.Scan(
			&i.ID,
			&i.Bab,
			&i.Judul,
			&i.IsiMd,
			&i.Urutan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPengurus = `-- name: ListPengurus :many
SELECT u.id, u.nama, u.no_wa, u.alamat, u.detail, u.foto_media_id, up.peran, up.gang
FROM user_peran up
JOIN user u ON u.id = up.user_id
WHERE up.peran IN ('ketua','wakil','sekretaris','bendahara','koordinator','pembantu_koordinator')
ORDER BY up.urutan, u.id
`

type ListPengurusRow struct {
	ID          int64
	Nama        string
	NoWa        string
	Alamat      sql.NullString
	Detail      sql.NullString
	FotoMediaID sql.NullInt64
	Peran       string
	Gang        int64
}

func (q *Queries) ListPengurus(ctx context.Context) ([]ListPengurusRow, error) {
	rows, err := q.db.QueryContext(ctx, listPengurus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPengurusRow
	for rows.Next() {
		var i ListPengurusRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.NoWa,
			&i.Alamat,
			&i.Detail,
			&i.FotoMediaID,
			&i.Peran,
			&i.Gang,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rumahUser = `-- name: RumahUser :one
SELECT r.id, r.alamat, r.blok, r.gang, r.status, ph.nama_kk, ph.jumlah_anggota, ph.status_huni
FROM user u
JOIN penghuni ph ON ph.id = u.penghuni_id
JOIN rumah r ON r.id = ph.rumah_id
WHERE u.id = ?
`

type RumahUserRow struct {
	ID            int64
	Alamat        string
	Blok          string
	Gang          int64
	Status        string
	NamaKk        string
	JumlahAnggota int64
	StatusHuni    string
}

func (q *Queries) RumahUser(ctx context.Context, id int64) (RumahUserRow, error) {
	row := q.db.QueryRowContext(ctx, rumahUser, id)
	var i RumahUserRow
	err := row.Scan(
		&i.ID,
		&i.Alamat,
		&i.Blok,
		&i.Gang,
		&i.Status,
		&i.NamaKk,
		&i.JumlahAnggota,
		&i.StatusHuni,
	)
	return i, err
}
