// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: media.sql

package db

import (
	"context"
)

const mediaByID = `-- name: MediaByID :one
SELECT id, path, thumb_path, mime, ukuran, akses, pemilik_user_id, hapus_setelah, dibuat_at
FROM media
WHERE id = ?
`

func (q *Queries) MediaByID(ctx context.Context, id int64) (Medium, error) {
	row := q.db.QueryRowContext(ctx, mediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ThumbPath,
		&i.Mime,
		&i.Ukuran,
		&i.Akses,
		&i.PemilikUserID,
		&i.HapusSetelah,
		&i.DibuatAt,
	)
	return i, err
}
