// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Agenda struct {
	ID         int64
	Judul      string
	Keterangan sql.NullString
	Mulai      string
	Selesai    sql.NullString
	Tingkat    string
	Gang       sql.NullInt64
	RutinID    sql.NullInt64
}

type Album struct {
	ID            int64
	Judul         string
	Slug          string
	Tanggal       string
	Cerita        sql.NullString
	SampulMediaID sql.NullInt64
	DibuatOleh    int64
}

type AlbumFoto struct {
	AlbumID    int64
	MediaID    int64
	Keterangan sql.NullString
	Urutan     int64
}

type AturanPasal struct {
	ID     string
	Bab    string
	Judul  string
	IsiMd  string
	Urutan int64
}

type AuditLog struct {
	ID      int64
	UserID  sql.NullInt64
	Aksi    string
	Objek   string
	ObjekID sql.NullString
	Detail  sql.NullString
	Ip      sql.NullString
	At      string
}

type Inventari struct {
	ID           int64
	Nama         string
	Kategori     sql.NullString
	Jumlah       sql.NullString
	Lokasi       sql.NullString
	Kondisi      string
	Catatan      sql.NullString
	BisaDipinjam int64
}

type JadwalRutin struct {
	ID     int64
	Judul  string
	Aturan string
	Gang   sql.NullInt64
	Aktif  int64
}

type KodeCadangan struct {
	KodeHash    string
	UserID      int64
	DibuatOleh  int64
	Kedaluwarsa string
	DipakaiAt   sql.NullString
}

type Medium struct {
	ID            int64
	Path          string
	ThumbPath     sql.NullString
	Mime          string
	Ukuran        int64
	Akses         string
	PemilikUserID sql.NullInt64
	HapusSetelah  sql.NullString
	DibuatAt      string
}

type Mutasi struct {
	ID               int64
	PosID            string
	Tanggal          string
	Arah             string
	Nominal          int64
	Kategori         string
	Keterangan       string
	KeteranganPublik string
	NotaMediaID      sql.NullInt64
	RefTipe          sql.NullString
	RefID            sql.NullInt64
	KoreksiDari      sql.NullInt64
	DibuatOleh       int64
	DibuatAt         string
}

type NotifOutbox struct {
	ID           int64
	NoWa         string
	Template     string
	Payload      string
	Status       string
	Percobaan    int64
	KirimSetelah string
	Error        sql.NullString
}

type Otp struct {
	NoWa        string
	KodeHash    string
	Kedaluwarsa string
	Percobaan   int64
}

type Pembayaran struct {
	ID           int64
	TagihanID    int64
	Metode       string
	Status       string
	DicatatOleh  int64
	DicatatAt    string
	BuktiMediaID sql.NullInt64
	SetoranID    sql.NullInt64
}

type Peminjaman struct {
	ID           int64
	InventarisID int64
	PengajuanID  sql.NullInt64
	Mulai        string
	Selesai      string
	Status       string
}

type Pengajuan struct {
	ID              int64
	Jenis           string
	RumahID         int64
	DiajukanOleh    int64
	Data            string
	Nominal         sql.NullInt64
	Status          string
	DitanganiOleh   sql.NullInt64
	CatatanPengurus sql.NullString
	DibuatAt        string
	DiubahAt        string
}

type Penghuni struct {
	ID                  int64
	RumahID             int64
	NamaKk              string
	Gender              sql.NullString
	TahunLahir          sql.NullInt64
	TahunLahirPerkiraan int64
	JumlahAnggota       int64
	StatusHuni          string
	Mulai               string
	Selesai             sql.NullString
	NoWa                sql.NullString
}

type Pengumuman struct {
	ID          int64
	Judul       string
	Isi         string
	Tingkat     string
	TerbitAt    string
	Kedaluwarsa sql.NullString
	KirimWa     int64
}

type PeriodeTutup struct {
	Periode       string
	DitutupOleh   int64
	DitutupAt     string
	SnapshotSaldo string
	PdfMediaID    sql.NullInt64
}

type PosDana struct {
	ID     string
	Nama   string
	Publik int64
}

type Rumah struct {
	ID               int64
	Alamat           string
	Blok             string
	Nomor            string
	Gang             int64
	Status           string
	BebasIuranAlasan sql.NullString
	CatatanValidasi  sql.NullString
}

type Setoran struct {
	ID               int64
	Gang             int64
	Periode          string
	KoordinatorID    int64
	Total            int64
	Status           string
	DibuatAt         string
	DikonfirmasiOleh sql.NullInt64
	DikonfirmasiAt   sql.NullString
	Catatan          sql.NullString
}

type Setting struct {
	Key       string
	Value     string
	UpdatedAt string
}

type Surat struct {
	ID             int64
	PengajuanID    int64
	Nomor          string
	KodeVerifikasi string
	DibatalkanAt   sql.NullString
	PdfMediaID     sql.NullInt64
}

type Tagihan struct {
	ID         int64
	RumahID    int64
	PenghuniID sql.NullInt64
	Jenis      string
	Periode    string
	Nominal    int64
}

type User struct {
	ID           int64
	Nama         string
	NoWa         string
	PenghuniID   sql.NullInt64
	Aktif        int64
	AktifSampai  sql.NullString
	CreatedAt    string
	PasswordHash sql.NullString
	Alamat       sql.NullString
	Detail       sql.NullString
	FotoMediaID  sql.NullInt64
	Username     sql.NullString
}

type UserPeran struct {
	UserID int64
	Peran  string
	Gang   int64
	Urutan int64
}
