// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rumah.sql

package db

import (
	"context"
	"database/sql"
)

const listRumah = `-- name: ListRumah :many
SELECT r.alamat, r.blok, r.nomor, r.gang, r.status, r.bebas_iuran_alasan,
       COALESCE(ph.nama_kk, '') AS nama_kk, ph.jumlah_anggota, r.catatan_validasi
FROM rumah r
LEFT JOIN penghuni ph ON ph.rumah_id = r.id AND ph.selesai IS NULL
ORDER BY r.gang, r.blok, r.nomor
`

type ListRumahRow struct {
	Alamat           string
	Blok             string
	Nomor            string
	Gang             int64
	Status           string
	BebasIuranAlasan sql.NullString
	NamaKk           string
	JumlahAnggota    sql.NullInt64
	CatatanValidasi  sql.NullString
}

func (q *Queries) ListRumah(ctx context.Context) ([]ListRumahRow, error) {
	rows, err := q.db.QueryContext(ctx, listRumah)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRumahRow
	for rows.Next() {
		var i ListRumahRow
		if err := rows.Scan(
			&i.Alamat,
			&i.Blok,
			&i.Nomor,
			&i.Gang,
			&i.Status,
			&i.BebasIuranAlasan,
			&i.NamaKk,
			&i.JumlahAnggota,
			&i.CatatanValidasi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetoranSemua = `-- name: ListSetoranSemua :many
SELECT s.gang, s.periode, s.total, s.status, s.dibuat_at, COALESCE(u.nama, '') AS koordinator
FROM setoran s
LEFT JOIN user u ON u.id = s.koordinator_id
ORDER BY s.dibuat_at DESC
`

type ListSetoranSemuaRow struct {
	Gang        int64
	Periode     string
	Total       int64
	Status      string
	DibuatAt    string
	Koordinator string
}

func (q *Queries) ListSetoranSemua(ctx context.Context) ([]ListSetoranSemuaRow, error) {
	rows, err := q.db.QueryContext(ctx, listSetoranSemua)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSetoranSemuaRow
	for rows.Next() {
		var i ListSetoranSemuaRow
		if err := rows.Scan(
			&i.Gang,
			&i.Periode,
			&i.Total,
			&i.Status,
			&i.DibuatAt,
			&i.Koordinator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
