// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: undangan.sql

package db

import (
	"context"
)

const buatUndangan = `-- name: BuatUndangan :one
INSERT INTO undangan (judul, isi, terbit_at, dibuat_oleh) VALUES (?, ?, ?, ?) RETURNING id
`

type BuatUndanganParams struct {
	Judul      string
	Isi        string
	TerbitAt   string
	DibuatOleh int64
}

func (q *Queries) BuatUndangan(ctx context.Context, arg BuatUndanganParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, buatUndangan,
		arg.Judul,
		arg.Isi,
		arg.TerbitAt,
		arg.DibuatOleh,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listUndangan = `-- name: ListUndangan :many
SELECT id, judul, isi, terbit_at, dibuat_oleh FROM undangan ORDER BY id DESC
`

func (q *Queries) ListUndangan(ctx context.Context) ([]Undangan, error) {
	rows, err := q.db.QueryContext(ctx, listUndangan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Undangan
	for rows.Next() {
		var i Undangan
		if err := rows.Scan(
			&i.ID,
			&i.Judul,
			&i.Isi,
			&i.TerbitAt,
			&i.DibuatOleh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rsvpCount = `-- name: RsvpCount :one
SELECT
  CAST(SUM(CASE WHEN jawaban = 'hadir' THEN 1 ELSE 0 END) AS INTEGER) AS hadir,
  CAST(SUM(CASE WHEN jawaban = 'tidak' THEN 1 ELSE 0 END) AS INTEGER) AS tidak
FROM rsvp WHERE undangan_id = ?
`

type RsvpCountRow struct {
	Hadir int64
	Tidak int64
}

func (q *Queries) RsvpCount(ctx context.Context, undanganID int64) (RsvpCountRow, error) {
	row := q.db.QueryRowContext(ctx, rsvpCount, undanganID)
	var i RsvpCountRow
	err := row.Scan(&i.Hadir, &i.Tidak)
	return i, err
}

const rsvpJawaban = `-- name: RsvpJawaban :one
SELECT jawaban FROM rsvp WHERE undangan_id = ? AND rumah_id = ?
`

type RsvpJawabanParams struct {
	UndanganID int64
	RumahID    int64
}

func (q *Queries) RsvpJawaban(ctx context.Context, arg RsvpJawabanParams) (string, error) {
	row := q.db.QueryRowContext(ctx, rsvpJawaban, arg.UndanganID, arg.RumahID)
	var jawaban string
	err := row.Scan(&jawaban)
	return jawaban, err
}

const setRsvp = `-- name: SetRsvp :exec
INSERT INTO rsvp (undangan_id, rumah_id, jawaban, dijawab_at) VALUES (?, ?, ?, ?)
ON CONFLICT(undangan_id, rumah_id) DO UPDATE SET jawaban = excluded.jawaban, dijawab_at = excluded.dijawab_at
`

type SetRsvpParams struct {
	UndanganID int64
	RumahID    int64
	Jawaban    string
	DijawabAt  string
}

func (q *Queries) SetRsvp(ctx context.Context, arg SetRsvpParams) error {
	_, err := q.db.ExecContext(ctx, setRsvp,
		arg.UndanganID,
		arg.RumahID,
		arg.Jawaban,
		arg.DijawabAt,
	)
	return err
}

const undanganByID = `-- name: UndanganByID :one
SELECT id, judul, isi, terbit_at, dibuat_oleh FROM undangan WHERE id = ?
`

func (q *Queries) UndanganByID(ctx context.Context, id int64) (Undangan, error) {
	row := q.db.QueryRowContext(ctx, undanganByID, id)
	var i Undangan
	err := row.Scan(
		&i.ID,
		&i.Judul,
		&i.Isi,
		&i.TerbitAt,
		&i.DibuatOleh,
	)
	return i, err
}

const wajibIuranRumahCount = `-- name: WajibIuranRumahCount :one
SELECT COUNT(*) AS total FROM rumah WHERE status != 'kosong' AND bebas_iuran_alasan IS NULL
`

func (q *Queries) WajibIuranRumahCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, wajibIuranRumahCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}
