// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const listUser = `-- name: ListUser :many
SELECT u.id, u.nama, u.no_wa, u.alamat, u.detail, u.aktif, u.foto_media_id,
       (SELECT group_concat(up.peran, ',') FROM user_peran up WHERE up.user_id = u.id) AS peran
FROM user u
ORDER BY u.id
`

type ListUserRow struct {
	ID          int64
	Nama        string
	NoWa        string
	Alamat      sql.NullString
	Detail      sql.NullString
	Aktif       int64
	FotoMediaID sql.NullInt64
	Peran       string
}

func (q *Queries) ListUser(ctx context.Context) ([]ListUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRow
	for rows.Next() {
		var i ListUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.NoWa,
			&i.Alamat,
			&i.Detail,
			&i.Aktif,
			&i.FotoMediaID,
			&i.Peran,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE user SET nama = ?, no_wa = ?, alamat = ?, detail = ? WHERE id = ?
`

type UpdateUserParams struct {
	Nama   string
	NoWa   string
	Alamat sql.NullString
	Detail sql.NullString
	ID     int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Nama,
		arg.NoWa,
		arg.Alamat,
		arg.Detail,
		arg.ID,
	)
	return err
}

const userByID = `-- name: UserByID :one
SELECT id, nama, no_wa, alamat, detail, aktif, foto_media_id FROM user WHERE id = ?
`

type UserByIDRow struct {
	ID          int64
	Nama        string
	NoWa        string
	Alamat      sql.NullString
	Detail      sql.NullString
	Aktif       int64
	FotoMediaID sql.NullInt64
}

func (q *Queries) UserByID(ctx context.Context, id int64) (UserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, userByID, id)
	var i UserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.NoWa,
		&i.Alamat,
		&i.Detail,
		&i.Aktif,
		&i.FotoMediaID,
	)
	return i, err
}
